[package]
name = "gazo-gui"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "gazo-gui"
path = "src/main.rs"

[dependencies]
slint.workspace = true
gazo-core = { path = "../gazo-core" }
log.workspace = true

[build-dependencies]
slint-build.workspace = true
