[package]
name = "gazo-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
oxcrypt-core.workspace = true
thiserror.workspace = true
image.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
uuid.workspace = true
base64.workspace = true

[dev-dependencies]
tempfile.workspace = true
